services:
  # PostgreSQL数据库
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: datalabels
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # 使用不同端口避免冲突
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # 使用不同端口避免冲突
    restart: unless-stopped

volumes:
  postgres_data: